let products = JSON.parse(`[
  {
      "id": 59553,
      "campus": "hr-rpp",
      "name": "Camo Onesie",
      "slogan": "Blend in to your crowd",
      "description": "The So Fatigues will wake you up and fit you in. This high energy camo will have you blending in to even the wildest surroundings.",
      "category": "Jackets",
      "default_price": "140.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59554,
      "campus": "hr-rpp",
      "name": "Bright Future Sunglasses",
      "slogan": "You've got to wear shades",
      "description": "Where you're going you might not need roads, but you definitely need some shades. Give those baby blues a rest and let the future shine bright on these timeless lenses.",
      "category": "Accessories",
      "default_price": "69.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59555,
      "campus": "hr-rpp",
      "name": "Morning Joggers",
      "slogan": "Make yourself a morning person",
      "description": "Whether you're a morning person or not.  Whether you're gym bound or not.  Everyone looks good in joggers.",
      "category": "Pants",
      "default_price": "40.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59556,
      "campus": "hr-rpp",
      "name": "Slacker's Slacks",
      "slogan": "Comfortable for everything, or nothing",
      "description": "I'll tell you how great they are after I nap for a bit.",
      "category": "Pants",
      "default_price": "65.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59557,
      "campus": "hr-rpp",
      "name": "Heir Force Ones",
      "slogan": "A sneaker dynasty",
      "description": "Now where da boxes where I keep mine? You should peep mine, maybe once or twice but never three times. I'm just a sneaker pro, I love Pumas and shell toes, but can't nothin compare to a fresh crispy white pearl",
      "category": "Kicks",
      "default_price": "99.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59558,
      "campus": "hr-rpp",
      "name": "Pumped Up Kicks",
      "slogan": "Faster than a just about anything",
      "description": "The Pumped Up serves up crisp court style with a modern look. These shoes show off tennis-whites shades and are constructed with a supple leather upper and a classic rubber cupsole.",
      "category": "Kicks",
      "default_price": "89.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59559,
      "campus": "hr-rpp",
      "name": "Blues Suede Shoes",
      "slogan": "2019 Stanley Cup Limited Edition",
      "description": "Touch down in the land of the Delta Blues in the middle of the pouring rain",
      "category": "Dress Shoes",
      "default_price": "120.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59560,
      "campus": "hr-rpp",
      "name": "YEasy 350",
      "slogan": "Just jumped over jumpman",
      "description": "These stretchy knit shoes show off asymmetrical lacing and a big sculpted rubber midsole. In a nod to adidas soccer heritage.",
      "category": "Kicks",
      "default_price": "450.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59561,
      "campus": "hr-rpp",
      "name": "Summer Shoes",
      "slogan": "A risky call in the spring or fall",
      "description": "Low-top panelled buffed leather and mesh sneakers. Sizing embroidered in black at round toe. Tonal lace-up closure. Pull-loop and rubberized style name at padded tongue. Padded collar. Pull-loop at heel collar. Logo embroidered in black at outer side. Tonal treaded rubber sole. Tonal stitching.",
      "category": "Kicks",
      "default_price": "59.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59562,
      "campus": "hr-rpp",
      "name": "Infinity Stone",
      "slogan": "Reality is often disappointing. That is, it was. Now, reality can be whatever I want.",
      "description": "The Infinity Stones are six immensely powerful stone-like objects tied to different aspects of the universe, created by the Cosmic Entities. Each of the stones possesses unique capabilities that have been enhanced and altered by various alien civilizations for millennia.",
      "category": "Accessories",
      "default_price": "50000000.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59563,
      "campus": "hr-rpp",
      "name": "Air Minis 250",
      "slogan": "Full court support",
      "description": "This optimized air cushion pocket reduces impact but keeps a perfect balance underfoot.",
      "category": "Basketball Shoes",
      "default_price": "49.00",
      "created_at": "2021-10-18T22:50:41.839Z",
      "updated_at": "2021-10-18T22:50:41.839Z"
  },
  {
      "id": 59564,
      "campus": "hr-rpp",
      "name": "Alexys Shoes",
      "slogan": "Voluptatibus et nesciunt mollitia dolores pariatur est perferendis totam distinctio.",
      "description": "Quae quo sequi. Numquam et consequatur qui aperiam sed debitis iste. Placeat voluptatum est provident explicabo velit illum. Quis aspernatur qui consequuntur inventore veniam sint ipsum. Optio qui nihil illo provident possimus iure expedita. Blanditiis facilis quas voluptatum delectus nemo ut corrupti.",
      "category": "Shoes",
      "default_price": "35.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59565,
      "campus": "hr-rpp",
      "name": "The Don Shirt",
      "slogan": "Quia voluptatem impedit debitis et.",
      "description": "Nam ab placeat. Nostrum quisquam impedit occaecati eos quia culpa. Aliquam qui pariatur.",
      "category": "Shirt",
      "default_price": "181.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59566,
      "campus": "hr-rpp",
      "name": "The Edgar Sunglasses",
      "slogan": "Et magnam eum adipisci voluptatem ut voluptatem asperiores assumenda dolor.",
      "description": "Molestiae error excepturi ut officiis in quisquam repudiandae nisi nesciunt. Delectus animi atque velit veniam totam. Alias explicabo iure et saepe velit aut eligendi. Numquam sit accusantium. Voluptates dolores ea dicta.",
      "category": "Sunglasses",
      "default_price": "417.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59567,
      "campus": "hr-rpp",
      "name": "Alysson Suit",
      "slogan": "Qui facilis qui.",
      "description": "Voluptas unde quo aut vitae. Rem aut ratione et ex id consequatur neque inventore. Iste delectus quibusdam excepturi voluptatibus. Ratione dicta non blanditiis.",
      "category": "Suit",
      "default_price": "912.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59568,
      "campus": "hr-rpp",
      "name": "Micheal Shoes",
      "slogan": "Beatae est ea veniam magnam accusantium nulla aspernatur cumque quam.",
      "description": "Perspiciatis quisquam earum incidunt. Sed qui nemo dolores iste laborum. Beatae possimus tempore veniam repellendus alias ut vitae fugit culpa.",
      "category": "Shoes",
      "default_price": "403.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59569,
      "campus": "hr-rpp",
      "name": "Brown Boots",
      "slogan": "Iure explicabo magnam accusamus esse voluptatibus saepe.",
      "description": "Ex harum commodi qui tenetur. Quasi in unde eos. Aut non commodi sit aut non. Incidunt aut est rerum.",
      "category": "Boots",
      "default_price": "499.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59570,
      "campus": "hr-rpp",
      "name": "Constance Hoodie",
      "slogan": "Cum qui culpa adipisci corrupti excepturi et quisquam.",
      "description": "Ratione ea minima illum mollitia aut et. Quia ut quae sunt. Sint molestiae porro quia est. Facilis nihil sit nemo earum eaque recusandae quo consequatur a.",
      "category": "Hoodie",
      "default_price": "542.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59571,
      "campus": "hr-rpp",
      "name": "Lyda Backpack",
      "slogan": "Et sed architecto eos.",
      "description": "Consequuntur facere voluptatem nostrum minima similique necessitatibus sunt. Ut adipisci praesentium qui praesentium qui. Modi qui est optio fugiat vel numquam iste recusandae.",
      "category": "Backpack",
      "default_price": "512.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59572,
      "campus": "hr-rpp",
      "name": "Gideon Sweatpants",
      "slogan": "Et qui dignissimos libero esse.",
      "description": "Deserunt voluptas iste id sint eaque quia est delectus totam. A incidunt sit optio accusamus a ut. Temporibus non cumque quo expedita. Debitis omnis cupiditate quos perspiciatis aut adipisci unde.",
      "category": "Sweatpants",
      "default_price": "485.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59573,
      "campus": "hr-rpp",
      "name": "Bernardo 1300 Socks",
      "slogan": "Ut iste debitis.",
      "description": "Temporibus esse qui ut amet eum qui beatae. Fugit et dolores dolorem dolor hic ea cumque fuga. Nostrum sapiente commodi reprehenderit beatae blanditiis sapiente odio minus totam.",
      "category": "Socks",
      "default_price": "223.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59574,
      "campus": "hr-rpp",
      "name": "Ayana Sunglasses",
      "slogan": "Reprehenderit nulla reiciendis et modi quis optio ut aliquid et.",
      "description": "Qui ipsum occaecati commodi est nam et esse. Ut aut non. Velit dolores repudiandae voluptas quo ex non dignissimos.",
      "category": "Sunglasses",
      "default_price": "774.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59575,
      "campus": "hr-rpp",
      "name": "Gail Socks",
      "slogan": "Tempora nulla qui quia quis maiores.",
      "description": "Omnis ut animi consequuntur quae reiciendis perferendis. Molestias sed vel ut error hic incidunt aut quam. Libero repudiandae inventore sapiente. Nulla sed quia autem rerum quia a. Corporis repudiandae quas quasi minus expedita reprehenderit.",
      "category": "Socks",
      "default_price": "675.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59576,
      "campus": "hr-rpp",
      "name": "Leonie Heels",
      "slogan": "Officiis voluptatibus et error esse in velit ducimus.",
      "description": "Qui et quia consequatur hic dolorem necessitatibus. Ratione autem quasi omnis nesciunt quia quasi fugit. Dignissimos ab similique rem neque quis neque ut. Dignissimos et minima et at ipsa iste tempore. Consequuntur ut quia exercitationem voluptatum. Tempora neque est animi nam.",
      "category": "Heels",
      "default_price": "86.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59577,
      "campus": "hr-rpp",
      "name": "Erik Coat",
      "slogan": "Perferendis asperiores similique quis.",
      "description": "Quas inventore fugiat repellendus dolorem nesciunt ipsam. Maxime dignissimos ab pariatur ut et qui fugit voluptatem. Molestiae molestiae et corrupti sit eum.",
      "category": "Coat",
      "default_price": "33.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59578,
      "campus": "hr-rpp",
      "name": "Jovany Socks",
      "slogan": "Repellat rem illo numquam placeat et pariatur et.",
      "description": "Suscipit vero quam enim aut vel consequatur voluptatem architecto. Eum corrupti sed est ut ex rerum. Sunt quasi quis quam. Eos ratione ea facilis ullam exercitationem.",
      "category": "Socks",
      "default_price": "975.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59579,
      "campus": "hr-rpp",
      "name": "Aliya Trousers",
      "slogan": "Saepe dolor culpa error molestiae deleniti et voluptatem facilis deleniti.",
      "description": "Accusamus quaerat fuga quia impedit fugit aut sit enim. Totam eaque inventore iure quis repellat. Rerum ut reprehenderit.",
      "category": "Trousers",
      "default_price": "673.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59580,
      "campus": "hr-rpp",
      "name": "Ari Hoodie",
      "slogan": "Dicta ullam non non delectus magnam dignissimos eum cupiditate est.",
      "description": "Hic voluptas ad iusto iusto. Aliquid quia eum fugit maxime et expedita in laboriosam. Ex cupiditate unde consequatur velit. Eius aut occaecati debitis quae. Tenetur reprehenderit incidunt necessitatibus hic nam. Nulla ipsum provident officiis id consectetur est error.",
      "category": "Hoodie",
      "default_price": "131.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59581,
      "campus": "hr-rpp",
      "name": "Alberto Skirt",
      "slogan": "Nihil omnis asperiores maiores impedit quisquam dolore ducimus error.",
      "description": "Maxime aut pariatur voluptatem sapiente optio corrupti. Laboriosam aliquam vero est voluptas numquam et. Voluptatum beatae nam maiores nisi. Qui et quod quidem. Quo vel voluptates dolores. Adipisci ex laborum quia beatae necessitatibus.",
      "category": "Skirt",
      "default_price": "727.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59582,
      "campus": "hr-rpp",
      "name": "Devante Shoes",
      "slogan": "Et qui atque et.",
      "description": "Eligendi qui magni id veritatis repellendus et dolores. Sit sapiente pariatur ut est veritatis quod et. Et doloribus qui. Non facilis ab nemo voluptatem eveniet rerum. Esse consequatur itaque. Natus ut et ut.",
      "category": "Shoes",
      "default_price": "723.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59583,
      "campus": "hr-rpp",
      "name": "Shakira Dress",
      "slogan": "Hic ab aut voluptatem aut est iusto aut aliquid.",
      "description": "Et omnis quidem incidunt optio et molestiae. Dolores sunt nihil natus. Et et ut fugiat minima quae quos modi.",
      "category": "Dress",
      "default_price": "631.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59584,
      "campus": "hr-rpp",
      "name": "Gus Suit",
      "slogan": "Qui qui at modi suscipit quos saepe dolore.",
      "description": "Non a odio consequatur impedit ipsam aspernatur quia aut. Vel ea eum quos reprehenderit. Molestiae odit molestiae. Consequatur aut ipsa commodi omnis.",
      "category": "Suit",
      "default_price": "452.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59585,
      "campus": "hr-rpp",
      "name": "Wilfred Skirt",
      "slogan": "Accusantium eveniet harum ea.",
      "description": "Ratione debitis sapiente dignissimos velit quia. Quasi est occaecati id deserunt vel laborum tempora tempore. Dolorem dolor sint aliquid. Reiciendis autem impedit aliquam qui quis laudantium accusamus.",
      "category": "Skirt",
      "default_price": "736.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59586,
      "campus": "hr-rpp",
      "name": "Martin Jacket",
      "slogan": "In ea eligendi molestiae recusandae placeat sed dicta totam.",
      "description": "Est non ipsum velit qui velit. Molestias corporis corporis. Quas id quia adipisci dolores sunt vel. Quam maxime accusantium ut deserunt. Quibusdam corrupti et eum non repellendus omnis nihil corporis ea. Sapiente est eaque sequi aliquid.",
      "category": "Jacket",
      "default_price": "636.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59587,
      "campus": "hr-rpp",
      "name": "Cade Shoes",
      "slogan": "Asperiores sit et consectetur iste.",
      "description": "Odio ut enim. Tempora amet exercitationem ea error nulla est. Facilis laudantium assumenda quod ea ut animi vitae omnis accusantium.",
      "category": "Shoes",
      "default_price": "662.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59588,
      "campus": "hr-rpp",
      "name": "Kelli Shorts",
      "slogan": "At vitae voluptate tenetur excepturi temporibus rerum incidunt harum.",
      "description": "Consequatur cumque velit qui. Nulla dolore quod et exercitationem quisquam commodi. Aliquid alias voluptas sed quia quas iste. Iusto perspiciatis numquam quia optio ut. Et sit nisi.",
      "category": "Shorts",
      "default_price": "962.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59589,
      "campus": "hr-rpp",
      "name": "Katlynn Slacks",
      "slogan": "Et vel voluptatem.",
      "description": "Alias est voluptate ea quo praesentium unde. Ad qui itaque consequatur adipisci dicta ipsa. Sunt sint iure quibusdam odit. Voluptatem nihil iusto laborum ut.",
      "category": "Slacks",
      "default_price": "373.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59590,
      "campus": "hr-rpp",
      "name": "Vinnie Romper",
      "slogan": "Aliquam reprehenderit suscipit eum laborum iste molestias et fuga neque.",
      "description": "Odio rerum repellendus ut. Voluptatem fuga dolorum inventore cumque. Adipisci vero distinctio eum expedita.",
      "category": "Romper",
      "default_price": "167.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59591,
      "campus": "hr-rpp",
      "name": "Mustafa Pants",
      "slogan": "Sed maiores debitis ad.",
      "description": "Et rem aut quia ab. Molestiae est adipisci similique similique provident dolor unde dignissimos. Nulla possimus ut error et et qui sint. Sed eos et tempore. Itaque saepe inventore nobis.",
      "category": "Pants",
      "default_price": "183.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59592,
      "campus": "hr-rpp",
      "name": "Adele Hat",
      "slogan": "Autem et omnis repellat minus ad repudiandae soluta inventore.",
      "description": "Illum corporis aspernatur ipsa libero tempora et nam reiciendis sint. Dolores quibusdam rem consequatur recusandae esse totam sit. Vel repellendus ut officia cum et harum et ut consequatur. Eveniet consequatur sit dicta id rerum aut inventore. Similique mollitia nostrum distinctio provident praesentium in. Non dignissimos quisquam voluptas quasi.",
      "category": "Hat",
      "default_price": "456.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59593,
      "campus": "hr-rpp",
      "name": "Will Dress",
      "slogan": "Tempore adipisci aut quisquam nihil sunt enim repudiandae.",
      "description": "Nulla odit esse aperiam repellat accusantium asperiores laudantium beatae soluta. Qui voluptatibus eveniet eos omnis rerum id assumenda. Non optio soluta laudantium amet tempora ea.",
      "category": "Dress",
      "default_price": "761.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59594,
      "campus": "hr-rpp",
      "name": "Lola Jacket",
      "slogan": "Maxime quisquam consequatur aliquid est optio illo aperiam.",
      "description": "Harum quo quasi. Amet neque quis omnis non placeat. Mollitia tenetur eveniet dolorum. Officiis exercitationem provident harum eum veritatis iure minus voluptates. Ex itaque vel exercitationem facilis libero dolorum sint.",
      "category": "Jacket",
      "default_price": "276.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59595,
      "campus": "hr-rpp",
      "name": "Ima Tank Top",
      "slogan": "Quod ipsam et.",
      "description": "Placeat numquam fuga esse. Porro eum velit a. Est facilis natus reprehenderit explicabo illum deserunt voluptas doloremque. Ut inventore dolorum iure ut voluptatum est pariatur qui non. Voluptatem reprehenderit sint culpa iure sapiente eligendi nisi ipsam perspiciatis. Atque quas qui.",
      "category": "Tank Top",
      "default_price": "195.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59596,
      "campus": "hr-rpp",
      "name": "Sonia Romper",
      "slogan": "Sed enim cumque officiis sit asperiores.",
      "description": "Maxime id in sunt aut facilis. Sit ea unde molestiae dolore fugit. Expedita ad sed nemo tempore cum dolor. Voluptatem provident quaerat.",
      "category": "Romper",
      "default_price": "912.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59597,
      "campus": "hr-rpp",
      "name": "Brionna Socks",
      "slogan": "Qui aut sed non.",
      "description": "Laudantium iure quis aut ab autem id sint. Ullam quas perspiciatis rerum. Quisquam quo sit magnam nostrum eum voluptate enim a ratione. Rerum porro harum unde quibusdam non omnis. Nostrum id laudantium est.",
      "category": "Socks",
      "default_price": "766.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59598,
      "campus": "hr-rpp",
      "name": "Delfina Slacks",
      "slogan": "Quasi voluptatum excepturi placeat ducimus impedit incidunt dicta quo et.",
      "description": "Praesentium numquam dicta tempora autem. Delectus iusto est tempore velit distinctio. Sed enim dolore est consequatur nihil.",
      "category": "Slacks",
      "default_price": "389.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59599,
      "campus": "hr-rpp",
      "name": "Camylle Dress",
      "slogan": "Est dignissimos tenetur assumenda quia maxime quasi nostrum vero quo.",
      "description": "Deleniti mollitia hic explicabo. Et id laboriosam molestiae inventore voluptate. Magni autem enim totam et soluta molestias ut qui quia. Occaecati sunt ea nulla.",
      "category": "Dress",
      "default_price": "725.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59600,
      "campus": "hr-rpp",
      "name": "Nikolas Skirt",
      "slogan": "Nesciunt dolorem consequuntur aut aliquid iusto aut officia.",
      "description": "Ipsam qui nisi inventore eveniet qui nostrum accusamus. Ea rerum natus sunt sunt rerum fugit officia officiis. Animi tempore officia aut asperiores et esse maxime est.",
      "category": "Skirt",
      "default_price": "161.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59601,
      "campus": "hr-rpp",
      "name": "The Preston Backpack",
      "slogan": "Provident eius maiores.",
      "description": "Fugiat deleniti deleniti qui totam laborum molestiae soluta. Voluptate aut eaque. Doloremque nulla ut perspiciatis autem.",
      "category": "Backpack",
      "default_price": "553.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59602,
      "campus": "hr-rpp",
      "name": "Gilbert Trousers",
      "slogan": "Delectus non laudantium amet sint mollitia itaque in sapiente.",
      "description": "Beatae molestiae sapiente tempore unde harum nemo. Placeat mollitia natus sit ea quo neque aut dolor rerum. Excepturi qui fugiat odit harum rerum ad voluptatem expedita quasi. Dolorum est blanditiis. Qui sit aut sequi aut aut quis qui. Molestias enim qui et tempore dolores quasi ab ut.",
      "category": "Trousers",
      "default_price": "932.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59603,
      "campus": "hr-rpp",
      "name": "Arno Pants",
      "slogan": "Eius et nostrum nesciunt nobis quod similique consectetur accusamus.",
      "description": "Id vel nisi eaque rem consequatur. Vitae repellat qui tempore ipsam. Fugiat qui exercitationem ex ipsum et ut voluptates. Deleniti fugit sit et et molestiae est tenetur non. Iste quisquam quo. Reprehenderit assumenda quis voluptatem fugit perferendis odio qui.",
      "category": "Pants",
      "default_price": "705.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59604,
      "campus": "hr-rpp",
      "name": "Mitchel Skirt",
      "slogan": "Laborum rerum ut repellendus pariatur aut et doloribus qui.",
      "description": "Repellendus error dolor temporibus cum eum. Esse laboriosam quam voluptatibus. Et consequatur odit error ullam voluptatem. Non accusamus et perferendis quo et omnis cumque at.",
      "category": "Skirt",
      "default_price": "746.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59605,
      "campus": "hr-rpp",
      "name": "Leta Skirt",
      "slogan": "Porro molestiae eligendi magni.",
      "description": "Est voluptatem voluptas. Beatae quam dolorum nulla sequi et. In omnis consectetur magni non voluptatum sed et.",
      "category": "Skirt",
      "default_price": "648.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59606,
      "campus": "hr-rpp",
      "name": "The Nicole Cap",
      "slogan": "Sit sequi repudiandae assumenda molestias perferendis autem.",
      "description": "Porro porro dolores sed aut magni omnis. Et illo dignissimos voluptatem est enim. Expedita assumenda consequatur velit sunt voluptas est enim quia. Alias repudiandae assumenda ullam consequatur. Consectetur sit suscipit. Soluta autem at voluptatibus deleniti totam aut eligendi laboriosam qui.",
      "category": "Cap",
      "default_price": "924.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59607,
      "campus": "hr-rpp",
      "name": "Angelica Suit",
      "slogan": "Ut aperiam magnam alias voluptatem ab est reprehenderit qui.",
      "description": "Sed rerum quia et libero ut alias sint occaecati maiores. Mollitia non et. Quasi et debitis officiis.",
      "category": "Suit",
      "default_price": "340.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59608,
      "campus": "hr-rpp",
      "name": "Isabella Shoes",
      "slogan": "Velit sint nemo quo non incidunt sequi praesentium laboriosam.",
      "description": "Cum molestiae ratione explicabo. Omnis eius iusto nulla eaque dolore deserunt ipsum. Ea veritatis et in maxime voluptatum sit ut fugit saepe.",
      "category": "Shoes",
      "default_price": "829.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59609,
      "campus": "hr-rpp",
      "name": "Israel Shirt",
      "slogan": "Velit et iusto odio sed accusamus ex enim.",
      "description": "Mollitia officiis unde eos autem sit sit voluptas nobis asperiores. Harum inventore nulla et reprehenderit eum quo consequatur ullam inventore. Ducimus optio quia magni expedita tenetur aspernatur dolorum. Omnis ipsa consectetur quisquam inventore id. Ut id veniam dolorem.",
      "category": "Shirt",
      "default_price": "615.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59610,
      "campus": "hr-rpp",
      "name": "Berniece Heels",
      "slogan": "Autem doloremque atque aut velit consequatur et minus qui.",
      "description": "Perspiciatis sint fugit voluptatem. Reiciendis voluptates provident ut placeat. Ut incidunt ut.",
      "category": "Heels",
      "default_price": "880.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59611,
      "campus": "hr-rpp",
      "name": "Jada Cap",
      "slogan": "Et qui magni.",
      "description": "Minima labore velit ut occaecati aperiam aliquid odio. Quisquam est et et perspiciatis ex consequatur sequi. Blanditiis reprehenderit ut quos.",
      "category": "Cap",
      "default_price": "388.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59612,
      "campus": "hr-rpp",
      "name": "Marcelino Shorts",
      "slogan": "Ipsam cum qui aperiam omnis unde architecto dolores.",
      "description": "Nostrum provident sequi qui ratione dolor facere qui qui rerum. Quos ad ut voluptate quaerat aspernatur cum vel tempora est. Ut expedita et delectus veritatis architecto molestiae natus quae voluptates. A natus reprehenderit atque nobis illum cum ipsum. Rerum nam incidunt ut nobis.",
      "category": "Shorts",
      "default_price": "239.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59613,
      "campus": "hr-rpp",
      "name": "Lela Heels",
      "slogan": "Consequatur quis velit iure earum non id.",
      "description": "Nulla tempore expedita impedit nesciunt atque laborum eaque. Voluptatibus recusandae molestias sed voluptatum dignissimos molestias. Enim itaque consectetur consequuntur consequatur distinctio.",
      "category": "Heels",
      "default_price": "720.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59614,
      "campus": "hr-rpp",
      "name": "Nash Cap",
      "slogan": "Voluptas totam nam quis voluptas aperiam et molestias asperiores.",
      "description": "Aut quis officiis aspernatur consectetur dolorem et ab aperiam. Qui vel rerum velit praesentium quaerat eius cupiditate veritatis. Quia accusantium dolorem. Delectus provident natus vero tenetur qui sunt. Quis earum ipsum ratione voluptas soluta rerum natus voluptas rerum. Ab iure eum aut qui cum aperiam vel.",
      "category": "Cap",
      "default_price": "865.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59615,
      "campus": "hr-rpp",
      "name": "Kennedi Suit",
      "slogan": "Nihil voluptatem eaque.",
      "description": "Quo sequi sit. Sit consequuntur occaecati autem omnis temporibus. Odit laboriosam voluptatum sint rerum. Ut repellendus quos.",
      "category": "Suit",
      "default_price": "6.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59616,
      "campus": "hr-rpp",
      "name": "Fannie Pants",
      "slogan": "Animi eum ea corrupti quia reprehenderit enim dolorem.",
      "description": "Sit et culpa veritatis ipsam est error aut. Vel laboriosam et ut. In odio voluptatibus perspiciatis est illo impedit ut rerum. Velit asperiores delectus animi id. Quia maiores minima reiciendis doloribus omnis est ex a. Consectetur magnam eum velit ipsa necessitatibus et.",
      "category": "Pants",
      "default_price": "150.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59617,
      "campus": "hr-rpp",
      "name": "Greyson Sweatpants",
      "slogan": "Dolor magni dignissimos.",
      "description": "Mollitia quis non dicta est sed numquam facilis voluptatem. Nisi magnam dicta necessitatibus qui veniam autem accusamus ut. Officia dolorem quibusdam ipsa quia laboriosam reprehenderit similique facere. Quod voluptatem et dolore fugit nobis possimus eos id voluptas.",
      "category": "Sweatpants",
      "default_price": "587.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59618,
      "campus": "hr-rpp",
      "name": "Abigale Jacket",
      "slogan": "Ad dolores corrupti libero sint dicta perspiciatis.",
      "description": "Sunt aut nihil fugiat dolorem necessitatibus rerum repellendus provident. Laboriosam quia dolor quod temporibus ullam accusantium sunt sit. Accusantium omnis neque non voluptatem sed.",
      "category": "Jacket",
      "default_price": "899.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59619,
      "campus": "hr-rpp",
      "name": "Kennedy Slacks",
      "slogan": "Eos veritatis qui.",
      "description": "Voluptatum commodi porro quia modi. Eligendi aliquam suscipit impedit consectetur sit explicabo est praesentium. Earum qui laboriosam saepe magnam consequatur quaerat commodi fugit velit. Velit ut omnis est. Deleniti ut occaecati.",
      "category": "Slacks",
      "default_price": "885.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59620,
      "campus": "hr-rpp",
      "name": "The Emmanuel Shirt",
      "slogan": "Non consequatur aut est voluptatem non dolorum optio a eveniet.",
      "description": "In reprehenderit consequatur labore aliquam voluptatum quo porro dolore. Illo harum voluptate error et. Quis ea qui amet eos aspernatur aut voluptatum et.",
      "category": "Shirt",
      "default_price": "246.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59621,
      "campus": "hr-rpp",
      "name": "Shemar Sweatpants",
      "slogan": "Voluptatem et amet sed.",
      "description": "Dolorem nobis enim. Voluptas consequatur facere et. Id sit nulla quo odio eum. Quis magnam consequatur est veniam omnis cumque aliquam ut non. Debitis enim sit eius ipsa et fugiat omnis. Molestiae magnam et quia ipsum voluptas.",
      "category": "Sweatpants",
      "default_price": "926.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59622,
      "campus": "hr-rpp",
      "name": "Iva Backpack",
      "slogan": "Qui ea sapiente nesciunt eaque nam aliquid dicta consequatur.",
      "description": "Occaecati atque ex maiores corporis sed animi et at iure. Nisi consequatur accusantium aperiam ut est minus blanditiis. Cum similique velit blanditiis hic ea alias ea. Nam culpa rerum et deleniti porro ratione corporis.",
      "category": "Backpack",
      "default_price": "290.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59623,
      "campus": "hr-rpp",
      "name": "Otis Dress",
      "slogan": "Mollitia nam omnis qui excepturi voluptate officia deleniti dicta.",
      "description": "Voluptas aut adipisci perferendis. Fuga delectus repellat soluta ea minima eos laudantium quas maiores. Voluptatem consequatur aut voluptatem voluptatem similique rerum voluptatem officiis.",
      "category": "Dress",
      "default_price": "806.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59624,
      "campus": "hr-rpp",
      "name": "Henri 1200 Backpack",
      "slogan": "Voluptatum ipsa molestias officiis soluta sed harum delectus voluptatem.",
      "description": "Molestias aut illum et laborum nam iusto pariatur. Hic laudantium corporis eos dolor ad. Nihil in omnis voluptas provident laudantium consequatur consequatur sint mollitia. Tempora facere qui mollitia voluptates et.",
      "category": "Backpack",
      "default_price": "687.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59625,
      "campus": "hr-rpp",
      "name": "Adrienne Shirt",
      "slogan": "Delectus quis quibusdam.",
      "description": "Qui voluptatum qui quisquam eum odit. Dolor qui iusto iste. Animi molestiae omnis.",
      "category": "Shirt",
      "default_price": "246.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59626,
      "campus": "hr-rpp",
      "name": "Hershel Romper",
      "slogan": "Nulla laboriosam laborum tempore.",
      "description": "Qui labore quibusdam eius. Odit sed rerum eius eaque dicta quis. Repellat repudiandae fuga dolorum id et alias modi quaerat.",
      "category": "Romper",
      "default_price": "78.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59627,
      "campus": "hr-rpp",
      "name": "Dina Tank Top",
      "slogan": "Neque fugiat aut quia ipsum ullam cupiditate quasi ab.",
      "description": "Laboriosam et aut totam sed sint autem quia. Voluptatem modi eum itaque quisquam mollitia accusantium error. Dolores ab explicabo quos nobis omnis officia eveniet omnis.",
      "category": "Tank Top",
      "default_price": "374.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59628,
      "campus": "hr-rpp",
      "name": "Garry 1000 Sweatpants",
      "slogan": "Placeat cum nulla accusamus et culpa velit.",
      "description": "Nihil aut voluptas qui possimus ducimus ipsum ducimus quaerat. Sunt dolorem amet architecto esse illo nulla deserunt. Velit sapiente itaque quam minima recusandae. Nulla tempore nemo veniam asperiores facere et voluptatem sint mollitia.",
      "category": "Sweatpants",
      "default_price": "316.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59629,
      "campus": "hr-rpp",
      "name": "Heaven 700 Skirt",
      "slogan": "Ut est magnam nihil ipsam assumenda voluptas.",
      "description": "Velit blanditiis ullam. Voluptatem corporis reiciendis inventore dolores nemo ut pariatur quam. Rem enim provident cumque assumenda cupiditate. Animi consectetur quis aut quod et est quia et. Officia rerum dolorum qui non. Ut tempora ut consequatur modi veritatis id nesciunt.",
      "category": "Skirt",
      "default_price": "924.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59630,
      "campus": "hr-rpp",
      "name": "Hal Trousers",
      "slogan": "Deleniti enim fuga alias et rerum quo.",
      "description": "Pariatur sed blanditiis tempore ipsam. Quia reiciendis illum tempora fugiat esse assumenda quia dolorem qui. Rerum voluptatum in. Suscipit quo quaerat mollitia. Ea et exercitationem corporis harum.",
      "category": "Trousers",
      "default_price": "463.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59631,
      "campus": "hr-rpp",
      "name": "The Noemy Sunglasses",
      "slogan": "Sit unde consequatur nostrum veritatis unde.",
      "description": "Quo sunt debitis neque expedita doloremque dicta incidunt aut qui. Ad id libero aspernatur et debitis voluptatem. Qui dolore dolore culpa ut praesentium atque recusandae rerum earum. Velit facere quisquam error id repudiandae perferendis quaerat architecto fuga.",
      "category": "Sunglasses",
      "default_price": "703.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59632,
      "campus": "hr-rpp",
      "name": "Valentina Backpack",
      "slogan": "Illo est fugiat suscipit.",
      "description": "Non accusantium et ab sunt nemo voluptatem sit delectus quam. Qui voluptatem quibusdam impedit aut facere. Fugiat quo autem commodi totam. Corporis minus voluptas aut voluptates enim magnam soluta libero.",
      "category": "Backpack",
      "default_price": "144.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59633,
      "campus": "hr-rpp",
      "name": "Gwen Socks",
      "slogan": "Nostrum error aut dolorem.",
      "description": "Eveniet alias aliquam qui veniam corrupti perspiciatis. Facere et sed inventore modi. Tempore ipsum velit.",
      "category": "Socks",
      "default_price": "109.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59634,
      "campus": "hr-rpp",
      "name": "Tia Shoes",
      "slogan": "Exercitationem fuga provident reiciendis est id et.",
      "description": "Fugiat tenetur exercitationem et quis officia et. Cum facilis deserunt. Facilis quisquam sunt vero commodi occaecati aut aut sunt sunt.",
      "category": "Shoes",
      "default_price": "586.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59635,
      "campus": "hr-rpp",
      "name": "Daphney Boots",
      "slogan": "Nam et possimus praesentium occaecati.",
      "description": "Reprehenderit officiis iure. Voluptas consequatur et inventore aliquam eos. Debitis optio animi et ullam rerum sit. Hic dicta quaerat ea ut id suscipit minus. Suscipit tenetur praesentium fugit quos ut accusantium debitis non velit.",
      "category": "Boots",
      "default_price": "612.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59636,
      "campus": "hr-rpp",
      "name": "Abraham Sweater",
      "slogan": "Est eveniet aut adipisci repellat rem voluptas dolorem et.",
      "description": "Rem veritatis ut. Nihil ad ratione nisi ut quidem mollitia earum. Modi blanditiis cum. Suscipit sapiente molestiae.",
      "category": "Sweater",
      "default_price": "23.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59637,
      "campus": "hr-rpp",
      "name": "Raphaelle Hat",
      "slogan": "Harum voluptatibus nam incidunt vitae aut velit qui.",
      "description": "Voluptates at quaerat debitis deleniti id excepturi quis quam officia. Tenetur qui dolorem rerum esse eum laudantium soluta. Qui animi nemo voluptate culpa quae. Ut inventore voluptas quod voluptas omnis aut magni veniam.",
      "category": "Hat",
      "default_price": "959.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59638,
      "campus": "hr-rpp",
      "name": "Rafaela Tank Top",
      "slogan": "Quo velit laboriosam et tempora enim asperiores dicta.",
      "description": "Magni cumque delectus consectetur porro qui. Voluptatem sed aut odio. Autem qui fugit deserunt sit modi. Et aut provident ipsam commodi sed dolor id porro voluptates. Natus eos sunt.",
      "category": "Tank Top",
      "default_price": "91.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59639,
      "campus": "hr-rpp",
      "name": "Gloria Slacks",
      "slogan": "Porro ex dicta corrupti ratione et.",
      "description": "Illo est porro. Sunt vero earum error molestiae. Quae doloremque ipsum enim nihil aut consequatur error quasi. Sunt minima eum repellendus magnam a vel sit delectus dolores. Et iste iure qui qui architecto modi voluptas asperiores nisi.",
      "category": "Slacks",
      "default_price": "725.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59640,
      "campus": "hr-rpp",
      "name": "Brant Sweater",
      "slogan": "Est excepturi placeat quo omnis veniam.",
      "description": "Pariatur omnis aut. Voluptatem asperiores ipsa non sit rerum non quia. Exercitationem tempore voluptas. Dicta minima quia quasi quod doloribus voluptatem qui. Dicta sint suscipit accusantium qui aut quos. Atque neque quos sed tempora et voluptatem excepturi.",
      "category": "Sweater",
      "default_price": "831.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59641,
      "campus": "hr-rpp",
      "name": "Leanna Sweatpants",
      "slogan": "Eligendi sed reprehenderit nesciunt ullam repudiandae.",
      "description": "Eos minima non reprehenderit. Repellendus culpa minus amet. Fugiat voluptas ab hic sit. Et temporibus eveniet ut amet magnam veritatis in quis dolorem.",
      "category": "Sweatpants",
      "default_price": "344.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59642,
      "campus": "hr-rpp",
      "name": "Corine Shorts",
      "slogan": "Dolorem culpa quis.",
      "description": "Debitis itaque dolor quia minima dignissimos voluptas et est accusamus. Adipisci dolor consectetur labore perspiciatis quos magni atque. Et voluptas nihil voluptatem minima dolores quasi hic quo eaque. Expedita et et id qui sit totam eius. Ad est facere inventore reiciendis quos odio sed odit est. Fugiat ipsa doloremque.",
      "category": "Shorts",
      "default_price": "139.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59643,
      "campus": "hr-rpp",
      "name": "Brennan Dress",
      "slogan": "Veritatis enim dolor.",
      "description": "Repellendus ratione alias temporibus incidunt. Molestias et consectetur et dignissimos cupiditate. Voluptate aut et. Nihil reprehenderit pariatur ut.",
      "category": "Dress",
      "default_price": "526.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59644,
      "campus": "hr-rpp",
      "name": "Rose Hat",
      "slogan": "Libero sint totam.",
      "description": "In consequatur ea autem in quae. Ut pariatur voluptas tempore dicta ipsam maxime commodi eum. Atque delectus reprehenderit dignissimos quam aut. Doloremque possimus tenetur sit recusandae accusantium voluptate velit.",
      "category": "Hat",
      "default_price": "714.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59645,
      "campus": "hr-rpp",
      "name": "Ronny Backpack",
      "slogan": "Distinctio provident occaecati ad cum.",
      "description": "Aliquid alias quis. Minus quos suscipit rerum in exercitationem itaque eos voluptates hic. Rerum totam sit et quo est. Rerum molestiae necessitatibus sapiente a cum odio perferendis modi non.",
      "category": "Backpack",
      "default_price": "481.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59646,
      "campus": "hr-rpp",
      "name": "Stefanie Coat",
      "slogan": "Architecto ullam nisi pariatur ratione aut.",
      "description": "Ratione quisquam qui. Tempora rem dolores nobis. Maiores aliquid omnis perspiciatis labore error dicta perferendis sequi. Consequatur neque esse provident iusto consequatur ullam aut necessitatibus aut.",
      "category": "Coat",
      "default_price": "734.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59647,
      "campus": "hr-rpp",
      "name": "Immanuel Trousers",
      "slogan": "Nemo tenetur necessitatibus sunt sunt voluptate dolor ut hic.",
      "description": "Saepe sunt debitis at delectus voluptatum eveniet. Aperiam fugit error. Totam autem veniam. Sunt sit nam et dolore eum error. Minus doloribus et rerum quaerat dolorem eaque ad similique omnis. Illo voluptas laboriosam sunt.",
      "category": "Trousers",
      "default_price": "91.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59648,
      "campus": "hr-rpp",
      "name": "Evalyn 200 Shorts",
      "slogan": "Rerum ipsa tenetur exercitationem est quos aut dolorem sunt.",
      "description": "Doloremque voluptate id maxime eum illum laborum et. Voluptate voluptatem est magnam. Animi earum est pariatur laudantium architecto aliquid inventore est. Harum quo veritatis. Eaque et quod deserunt enim quaerat fuga.",
      "category": "Shorts",
      "default_price": "343.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59649,
      "campus": "hr-rpp",
      "name": "Sierra Sweater",
      "slogan": "Et soluta minus eum corrupti impedit.",
      "description": "Dolorem expedita harum ex. Sit eum architecto pariatur sunt sint sequi temporibus commodi veniam. Ullam nulla consequatur ut ducimus. Est cupiditate voluptatem est neque cumque labore quis iste quo. Ut sit natus facere et. Voluptate nemo enim sapiente sapiente consequatur totam quidem.",
      "category": "Sweater",
      "default_price": "338.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59650,
      "campus": "hr-rpp",
      "name": "Hubert Skirt",
      "slogan": "Iusto error sint est eum ab iure est dignissimos soluta.",
      "description": "Voluptatum qui omnis labore distinctio cupiditate hic aut odio. In nostrum deleniti doloribus modi cupiditate voluptate. Eligendi sequi nihil provident et id iste id aut quas. Aut consequatur qui non tempora molestiae et praesentium unde.",
      "category": "Skirt",
      "default_price": "32.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59651,
      "campus": "hr-rpp",
      "name": "Nichole Slacks",
      "slogan": "Sit voluptatem ut libero quia nulla blanditiis expedita.",
      "description": "Dolorem quaerat cum ut aperiam neque accusantium et est adipisci. Nostrum blanditiis totam omnis esse dolorem quasi nihil. Ut dolores optio optio. Voluptatibus quisquam quam saepe blanditiis. Odio nemo veniam nihil.",
      "category": "Slacks",
      "default_price": "355.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  },
  {
      "id": 59652,
      "campus": "hr-rpp",
      "name": "Lauretta Shoes",
      "slogan": "Consectetur quas nam veritatis.",
      "description": "Officia commodi quia quos consequuntur ut est ea harum. Est necessitatibus distinctio dicta dolores est porro rem. Ut soluta dolorum libero aut ea quae tenetur ad voluptates. Dolor velit consectetur saepe enim labore. Quia consequatur dicta qui temporibus exercitationem perspiciatis est sapiente et.",
      "category": "Shoes",
      "default_price": "948.00",
      "created_at": "2021-10-18T22:50:41.954Z",
      "updated_at": "2021-10-18T22:50:41.954Z"
  }
]`);

export default products;